import os

LOCK_TIMEOUT_SECONDS = 3.0
LOCK_ACQUIRE_RETRY_INTERVAL = 0.1

PERSIST_DIR = os.path.expanduser("~/.agent_memory_sessions")

TMP_FILE_SUFFIX = ".tmp"
LOCK_FILE_SUFFIX = ".lock"

ERROR_PREFIX = "[AgentMemory] "
ERROR_SUFFIX = " - 操作失败，请检查配置或重试"

EXIT_CODE_SUCCESS = 0
EXIT_CODE_ERROR = 1
EXIT_CODE_LOCK_TIMEOUT = 2
EXIT_CODE_CORRUPTED = 3
EXIT_CODE_CONCURRENT = 4
EXIT_CODE_DUPLICATE = 5
EXIT_CODE_VERSION = 6

SESSION_VERSION = "1.0"

MAX_WARM_MEMORIES = 5

COLD_MEMORY_DEDUP_MODE_REJECT = "reject"
COLD_MEMORY_DEDUP_MODE_OVERWRITE = "overwrite"
COLD_MEMORY_DEDUP_MODE = COLD_MEMORY_DEDUP_MODE_REJECT
